# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: write
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Save build output
        uses: actions/upload-artifact@v1
        with:
          name: built-output
          path: ./docs
      - name: Load saved build output
        uses: actions/download-artifact@v1
        with:
          name: built-output
          path: ./docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs # The folder the action should deploy.
